// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTcN8mr-Ck9pgZ7YoBu680aQCLP3LIdM',
    appId: '1:437387878706:web:1875ae009f1609ad70372b',
    messagingSenderId: '437387878706',
    projectId: 'designplus-db',
    authDomain: 'designplus-db.firebaseapp.com',
    storageBucket: 'designplus-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRdEgaL-r_YkJnkuDkrNKxKYGoqwOM_g',
    appId: '1:437387878706:android:da6ce4585dc59b0a70372b',
    messagingSenderId: '437387878706',
    projectId: 'designplus-db',
    storageBucket: 'designplus-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHjS5bNFzw_p_NSCplQXCNz5t_XmES4I',
    appId: '1:437387878706:ios:77ce5f10d16bab7c70372b',
    messagingSenderId: '437387878706',
    projectId: 'designplus-db',
    storageBucket: 'designplus-db.firebasestorage.app',
    iosBundleId: 'com.example.designplus',
  );
}
